### ISSUE TITLE
Cannot install theme because gconftool command was not found

### ISSUE THREAD

**Issue by fturco** [chriskempson/base16-gnome-terminal#12]
I'm trying to install the base16 default dark theme for GNOME terminal, but I obtain the following error message (repeated many times):

```
$ source base16-default.dark.sh
bash: gconftool: command not found
```

I can't find a package in my GNU/Linux distribution (Parabola GNU/Linux-libre) that provides the "gconftool" command.

**Comment by jakern** [comment]
Same here. I even changed gconftool in the script to gconftool-2 and it still complains that gconftool is not found

**Comment by fturco** [comment]
Just wanted to clarify that in my case I'm using bash. Haven't tried with other shells.

**Comment by vshvedov** [comment]
Same here, Fedora 22, zsh

**Comment by Azd325** [comment]
It works with bash variant fine. I'm on Arch Linux.
```bash
~ $ bash base16-eighties.dark.sh 
~ $ 
```

**Comment by vsimonian** [comment]
It looks like the problem is in the following check in the scripts:

```bash
    if [[ -n "`$DCONF list $BASE_KEY_NEW/`" ]]; then
```

On certain systems, if you haven't yet modified any profile settings and saved them, this will evaluate falsly and the attempt to use dconf will be skipped. After failing to use dconf, the script will continue on to trying to use gconftool, which is deprecated and applicable only to GNOME/GTK 2.x.

A workaround is to visit the profile settings and change some setting (the easiest being the name) and then saving the profile. This will result in a profile ID being available to `dconf list`, and then the expression above evaluates truthfully and dconf is used.

To see what the script is seeing, you can run `dconf list /org/gnome/terminal/legacy/profiles:/` before and after doing so, and you should first see no results, and after saving the profile see something along the lines of `:UUID-goes-here/`.

**Comment by yalcin** [comment]
you have to check the 'Run command as login shell' checkbox on the gnome-terminal preferences.

**Comment by iamarcel** [comment]
Another workaround might be using the `dconf load` command. This is what I do in the setup script for my dotfiles (note that this will overwrite any existing profiles):

```sh
dconf load /org/gnome/terminal/legacy/profiles:/ < $DOTFILES/gnome-terminal.profile.dconf
```

Contents of `gnome-terminal.profile.dconf` (created with `dconf dump` after "manually" installing the theme):

```ini
[/]
list=['3e8b4ae6-05ed-4006-885c-f45a19778924']

[:3e8b4ae6-05ed-4006-885c-f45a19778924]
foreground-color='#c5c8c6'
visible-name='Base 16 Tomorrow Dark'
palette=['#1d1f21', '#cc6666', '#b5bd68', '#f0c674', '#81a2be', '#b294bb', '#8abeb7', '#c5c8c6', '#969896', '#cc6666', '#b5bd68', '#f0c674', '#81a2be', '#b294bb', '#8abeb7', '#ffffff']
use-theme-colors=false
use-theme-background=false
bold-color-same-as-fg=true
bold-color='#c5c8c6'
background-color='#1d1f21'
```

**Comment by jitendra42** [comment]
**Following worked for me:**
I cloned the repo and then modified 
`[[ -z "$GCONFTOOL" ]] && GCONFTOOL=gconftool` to `[[ -z "$GCONFTOOL" ]] && GCONFTOOL=gconftool-2` in _apply-colors.sh
https://github.com/Mayccoll/Gogh/blob/master/_apply-colors.sh#L134

**Comment by zoechi** [comment]
I got this error when I installed google webdesigner.
Installing package `gconf` fixed it.

**Comment by nipunsadvilkar** [comment]
**Resolved**
Change L79 from `gconftool` to `gconftool-2`

```
# Fallback for Gnome 2 and early Gnome 3
[[ -z "$GCONFTOOL" ]] && GCONFTOOL=gconftool-2
[[ -z "$BASE_KEY" ]] && BASE_KEY=/apps/gnome-terminal/profiles
```

**Comment by ElijahLynn** [comment]
I came across this on RHEL7 today, `gconftool` doesn't exist, but `gconftool-2` does.

**Comment by chriskempson** [comment]
This repo is deprecated. Please see: https://github.com/chriskempson/base16-gnome-terminal#deprecated
